version: '2'
services:
    pollssurveys-app:
        image: pollssurveys
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pollssurveys-mysql:3306/pollssurveys?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8580:8580
    pollssurveys-mysql:
        extends:
            file: mysql.yml
            service: pollssurveys-mysql
